server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mileage_point
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com:
      mileage: debug
